data_generation:
    seed: 9451
    max_objects:  16
    dt: 0.1

    # variables are defined as [min, max] and are sampled as Uniform(min, max) per data generator
    n_timesteps: [50, 101]
    lambda_b_in: [0.025, 0.050]
    lambda_b_enter: [0.025, 0.050]
    p_survival: [0.9, 1.0]
    p_meas: [0.8, 1.0]
    process_noise_variance: [0.25, 1.0]
    lambda_clutter: [5.0, 10.0]

    measurement_noise_stds: [0.5, 0.001745]  # from resolution values of realistic lidar model in good region of FOV

    n_avg_starting_objects: 3
    avg_gt_objects: 2.5

    field_of_view: # LIDAR
        min_range: 0.0
        max_range: 125.0
        min_theta: -3.14
        max_theta: 3.14

    birth_process:
        mean_pos: [0.0, 0.0]
        cov_pos: [[125.0, 0.0], [0.0, 125.0]]
        mean_vel: [0.0, 0.0]
        cov_vel: [[15.0, 0.0], [0.0, 15.0]]

    prediction_target: 'position_and_velocity'

    do_return_truth: False # Turn to false when training since we do not want to return truth
